name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Initialize Terraform
      working-directory: /home/joris/azure/terraform
      run: terraform init

    - name: Apply Terraform
      working-directory: /home/joris/azure/terraform
      run: terraform apply -auto-approve

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        az webapp deployment source config --name tp-azure-joris-ameline --resource-group webapp-rg --repo-url https://github.com/JorisPV/azure-webapp --branch main --manual-integration
